# -*- mode:python -*-

# Copyright (c) 2016 Georgia Institute of Technology
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')

if not env['CONF']['RUBY']:
    Return()

#=====================================================================
SimObject('OnyxLink.py', enums=['ONYXCDCType'], sim_objects=[
    'NetLink', 'AckLink', 'NetBridge', 'OnyxIntLink',
    'OnyxExtLink', 'OnyxBusLink'])
#=====================================================================
#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
SimObject('OnyxNetwork.py', sim_objects=[
    'OnyxNetwork', 'OnyxNetworkInterface', 'OnyxSwitcher',
    'OnyxBus'])
#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

Source('OnyxLink.cc')
Source('OnyxNetwork.cc')
Source('InportModule.cc')
Source('InterfaceModule.cc')
Source('NetLink.cc')
Source('VcState.cc')
Source('OutportModule.cc')
Source('Switcher.cc')
#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
Source('Bus.cc')
Source('BusCrossbar.cc')
Source('BusInport.cc')
Source('BusOutport.cc')
Source('BusSwitchManager.cc')
Source('RoutingTable.cc')
#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
Source('PathFinder.cc')
Source('SwitchManager.cc')
Source('CrossbarMatrix.cc')
Source('VirtualPath.cc')
Source('chunkBuffer.cc')
Source('chunk.cc')
Source('Ack.cc')
Source('NetBridge.cc')
